DROP SEQUENCE IF EXISTS SEQ_EG_TL_APL_BH_hajipur;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_APL_BH_biharsharif;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_APL_BH_danapur;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_APL_BH_muzaffarpur;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_APL_BH_sitamarhi;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_APL_BH_bhagalpur;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_APL_BH_katihar;

CREATE SEQUENCE SEQ_EG_TL_APL_BH_hajipur;
CREATE SEQUENCE SEQ_EG_TL_APL_BH_biharsharif;
CREATE SEQUENCE SEQ_EG_TL_APL_BH_danapur;
CREATE SEQUENCE SEQ_EG_TL_APL_BH_muzaffarpur;
CREATE SEQUENCE SEQ_EG_TL_APL_BH_sitamarhi;
CREATE SEQUENCE SEQ_EG_TL_APL_BH_bhagalpur;
CREATE SEQUENCE SEQ_EG_TL_APL_BH_katihar;


DROP SEQUENCE IF EXISTS SEQ_EG_TL_LN_BH_hajipur;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_LN_BH_biharsharif;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_LN_BH_danapur;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_LN_BH_muzaffarpur;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_LN_BH_sitamarhi;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_LN_BH_bhagalpur;
DROP SEQUENCE IF EXISTS SEQ_EG_TL_LN_BH_katihar;

CREATE SEQUENCE SEQ_EG_TL_LN_BH_hajipur;
CREATE SEQUENCE SEQ_EG_TL_LN_BH_biharsharif;
CREATE SEQUENCE SEQ_EG_TL_LN_BH_danapur;
CREATE SEQUENCE SEQ_EG_TL_LN_BH_muzaffarpur;
CREATE SEQUENCE SEQ_EG_TL_LN_BH_sitamarhi;
CREATE SEQUENCE SEQ_EG_TL_LN_BH_bhagalpur;
CREATE SEQUENCE SEQ_EG_TL_LN_BH_katihar;
